// GET
export const FETCH_CONFIG_MOVES_REQUEST = 'FETCH_CONFIG_MOVES_REQUEST'
export const FETCH_CONFIG_MOVES_SUCCESS = 'FETCH_CONFIG_MOVES_SUCCESS'
export const FETCH_CONFIG_MOVES_FAILURE = 'FETCH_CONFIG_MOVES_FAILURE'

// UPDATE
export const FETCH_UPDATE_MOVES_RULES_REQUEST = 'FETCH_UPDATE_MOVES_RULES_REQUEST'
export const FETCH_UPDATE_MOVES_RULES_SUCCESS = 'FETCH_UPDATE_MOVES_RULES_SUCCESS'
export const FETCH_UPDATE_MOVES_RULES_FAILURE = 'FETCH_UPDATE_MOVES_RULES_FAILURE'