export const FETCH_INSERT_RANKING_REQUEST = 'FETCH_INSERT_RANKING_REQUEST'
export const FETCH_INSERT_RANKING_SUCCESS = 'FETCH_INSERT_RANKING_SUCCESS'
export const FETCH_INSERT_RANKING_FAILURE = 'FETCH_INSERT_RANKING_FAILURE'

export const FETCH_GET_RANKING_REQUEST = 'FETCH_GET_RANKING_REQUEST'
export const FETCH_GET_RANKING_SUCCESS = 'FETCH_GET_RANKING_SUCCESS'
export const FETCH_GET_RANKING_FAILURE = 'FETCH_GET_RANKING_FAILURE'

export const FETCH_UPDATE_RANKING_REQUEST = 'FETCH_UPDATE_RANKING_REQUEST'
export const FETCH_UPDATE_RANKING_SUCCESS = 'FETCH_UPDATE_RANKING_SUCCESS'
export const FETCH_UPDATE_RANKING_FAILURE = 'FETCH_UPDATE_RANKING_FAILURE'

